### ISSUE TITLE
ReferenceError: util is not defined

### ISSUE THREAD

**Issue by picoloop** [jesusprubio/shodan-client.js#22]
Hello, first of all thanks for your great library :)

I am encountering an issue while trying your example.

```js
const client = require('shodan-client');

const searchOpts = {
  facets: 'port:100,country:100',
  // minify: false,
};
client
  .search('asterisk port:5061', 'myapikey', searchOpts)
  .then(res => {
    console.log('Result:');
    console.log(util.inspect(res, { depth: 6 }));
  })
  .catch(err => {
    console.log('Error:');
    console.log(err);
  });
```

Return : 

> Result:
> Error:
> ReferenceError: util is not defined
>     at client.host.then.res (/home/picoloop/workspace/shodan.js:11:17)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Am I missing something ? 
Thanks in advance for your help.

**Environment :**

- OS: Arch Linux
- Node.js version: v10.5.0

**Comment by jesusprubio** [comment]
Ei, thanks for the feedback 😄. You´re right, there was an error in the example. I´ve added this first lost line.
https://github.com/jesusprubio/shodan-client.js/blob/master/README.md#use

Moreover I have also changed the query, because now Shodan returns an empty results looking for Asterisk in port 5061.

**Comment by picoloop** [comment]
I can believe I didn't try that..
I was thinking `util` was an internal library of your project :disappointed_relieved: 

Thanks for your help!
